/*
 * File:    Broken	.java
 * Created: 7 September 2001
 * Author:  Stephen Jarvis
 */

/*
 * Ex3 Preamble:
 * For the heading controller I imagined just using if statements would result in lengthy code that's hard to follow so I chose to use arrays to reduce the possible square to choose at random later.
 * It prioritises moving towards the target as intended however this results into it frequently getting stuck in a loop when in a maze generated by Prim's Algorithm.
 * This is also true for the loopy maze as despite it being more open it struggles when in a corner with ends facing away from the target.
 * This is because the robot has to move away a square but then moves right back due to it being towards the target.
 * It can never finish the hill maze as the target is on the same x level as it and so it always oscillates up and down from the starting position.
 * It always finishes the blank maze in the fewest amount of steps as it never has to move away from the target.
 * 
 * To try increase the chance of solving the maze you could reintroduce some randomness similar to exercise 2 so that it eventually breaks out the loop and picks a new direction.
 * You could also make it so that it avoids squares it has recently been before to give the robot time to explore alternatives.
 */

import uk.ac.warwick.dcs.maze.logic.IRobot;

public class Explorer
{
    public int nonwallExits(IRobot robot) {
        int nonwalls = 0;
        for (int i = 0; i < 4; i++) {
			if (robot.look(IRobot.AHEAD+i) != IRobot.WALL) {
                nonwalls++;
            }
        }
        return nonwalls;
    }


}
